import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { AddEditModalProvider } from "@/context/AddEditModalContext";
import { TriggerProvider } from "@/context/TriggerContext";
import { ThemeContext } from "@/context/ThemeContext";
import { NotificationProvider } from "@/context/NotificationContext";

const font = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeContext>
          <NotificationProvider>
            <AddEditModalProvider>
              <TriggerProvider>{children}</TriggerProvider>
            </AddEditModalProvider>
          </NotificationProvider>
        </ThemeContext>
      </body>
    </html>
  );
}
